name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  APP_NAME: Water Log
  APP_MAIN_CLASS: de.tjark.waterlog.App
  APP_VENDOR: Anders Digital Studio
  APP_ID: de.tjark.waterlog

jobs:

  build:

    strategy:
      fail-fast: false

      matrix:
        include:

          - os: windows-latest
            package: msi
            icon: jpackage/icon.ico
            extension: msi

          - os: ubuntu-latest
            package: deb
            icon: jpackage/icon.png
            extension: deb

          - os: macos-latest
            package: dmg
            icon: jpackage/icon.icns
            extension: dmg

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - name: Make Gradle executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: Build application
        shell: bash
        run: ./gradlew :app:installDist

      - name: Read Version
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      # - name: Install WiX
      #   if: runner.os == 'Windows'
      #   run: choco install wixtoolset --yes

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg-dev

      - name: Package Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          jpackage `
            --type msi `
            --name "${{ env.APP_NAME }}" `
            --input "app/build/install/Water Log/lib" `
            --main-jar app.jar `
            --main-class "${{ env.APP_MAIN_CLASS }}" `
            --icon jpackage/icon.ico `
            --vendor "${{ env.APP_VENDOR }}" `
            --app-version $env:VERSION `
            --install-dir "Water Log" `
            --win-dir-chooser `
            --win-menu `
            --win-shortcut `
            --dest release

      - name: Rename Windows installer
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Get-ChildItem release -Filter *.msi |
          Rename-Item -NewName "WaterLog-$env:VERSION-Windows.msi"

      - name: Package Linux
        if: runner.os == 'Linux'
        run: |
          jpackage \
            --type deb \
            --name "water-log" \
            --input "app/build/install/Water Log/lib" \
            --main-jar app.jar \
            --main-class "${APP_MAIN_CLASS}" \
            --icon jpackage/icon.png \
            --vendor "${APP_VENDOR}" \
            --app-version "${VERSION}" \
            --linux-package-name "water-log" \
            --linux-shortcut \
            --linux-menu-group "Utility" \
            --dest release

      - name: Rename Linux installer
        if: runner.os == 'Linux'
        run: |
          mv release/*.deb release/WaterLog-${VERSION}-Linux.deb

      - name: Package macOS
        if: runner.os == 'macOS'
        run: |
          jpackage \
            --type dmg \
            --name "${APP_NAME}" \
            --input "app/build/install/Water Log/lib" \
            --main-jar app.jar \
            --main-class "${APP_MAIN_CLASS}" \
            --icon jpackage/icon.icns \
            --vendor "${APP_VENDOR}" \
            --app-version "${VERSION}" \
            --mac-package-name "Water Log" \
            --mac-package-identifier "de.tjark.waterlog" \
            --dest release

      - name: Rename macOS installer
        if: runner.os == 'macOS'
        run: |
          mv release/*.dmg release/WaterLog-${VERSION}-macOS.dmg


      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: release/*

  release:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*